# -*- coding: utf-8 -*-
"""Nisha Arya - MedCab2bw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QgJtWv9XEALfnx-d9cdKfQuxdJ8MIkgX
"""

#open and view data

import pandas as pd

url = 'https://github.com/michhottinger/MedCab2bw/blob/master/cannabis.csv?raw=true'
df = pd.read_csv(url)
df.head(5)

url2 = 'https://raw.githubusercontent.com/DNason1999/simple_repository/master/df.csv'
df2 = pd.read_csv(url2)

#clean data as needed and prep for joining
df.isnull().sum()

df.dtypes

df_1 = df[['Strain', 'Rating', 'Description']].sort_values('Strain', ascending=True)
df_1

df2.head()

df2t = df2.T

df2t.head()

df_2 = df2t.reset_index().rename(columns={'index': 'Strain', 1: 'race', 2: 'flavors', 3: 'effects', 4: 'positive', 5: 'negative', 6: 'medical'}).drop([0])
df_2.head()

df_2.dtypes

df_1['Strain']=df_1['Strain'] = df['Strain'].str.replace('-', ' ')
df_1.head()

#join dfs
df_join = df_2.set_index('Strain').join(df_1.set_index('Strain'))
df_join

df_join.shape

df_join.isnull().sum()

#df_final = df_join.drop('0', axis-1)

df_final = df_join.drop([0], axis=1)

df_final

df_final.shape

df_final['flavors'].value_counts()

